name: Psalm

on: [push]

jobs:
    psalm:
        name: Psalm
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '7.4'
                  extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
                  coverage: none

            - name: Create database
              run: |
                  sudo /etc/init.d/mysql start
                  mysql  -u root -proot -e 'CREATE DATABASE IF NOT EXISTS spatie_tests;'

            - name: Cache composer dependencies
              uses: actions/cache@v1
              with:
                  path: vendor
                  key: composer-${{ hashFiles('composer.lock') }}

            - name: Run composer install
              run: composer install -n --prefer-dist
              env:
                COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}

            - name: Prepare Laravel Application
              run: |
                  cp .env.ci .env
                  php artisan key:generate
                  php artisan migrate

            - name: Generate IDE helper files
              run: |
                  php artisan ide-helper:eloquent
                  php artisan ide-helper:generate
                  php artisan ide-helper:meta
                  php artisan ide-helper:models

            - name: Run psalm
              run: ./vendor/bin/psalm -c psalm.xml
